---
- name: Conditions
  hosts: all
  gather_facts : true #### for the global gatherfact
  tasks:
    - name: print os
      debug:
        msg: "This is Amazon machine"
      when: ansible_distribution == "CentOS" and ansible_os_family == "Redhat"
