---
- name: Conditions
  hosts: all
  gather_facts: true
  tasks:
    - name: print os
      debug:
        msg: "This is Amazon machine"
      when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"

