- name: Gather Fact
  hosts: all
  gather_facts : true #### for the global gatherfact
  tasks: 
    - name : print hello world
      debug:
        msg: "Hello World"
    - name : print os
      debug : 
        msg : "{{ansible_distribution}}"
    - name : print family
      debug :
        msg : "{{ansible_os_family}}"
    - name : print address
      debug :
        msg : "{{ansible_default_ipv4.address}}"